### ISSUE TITLE
Turn of scrolling

### ISSUE THREAD

**Issue by Carpenteri1** [Carpenteri1/Portfolio#90]
fix scrolling later, to borked atm

**Comment by rajgop1** [comment]
@Carpenteri1 
Could you please provide additional details and a screenshot for the issue you've mentioned? This would greatly assist in understanding the situation better and consequently finding an appropriate solution.

**Comment by Carpenteri1** [comment]
@rajgop1 At the moment Im not sure what the trouble is. The scrolling is broken at some sections, and you can't seem to be able to scroll up at all.
Will disable it for now and maybe add it in later again.

**Comment by rajgop1** [comment]
@Carpenteri1 Yes, It is happening in my case also, you can assign this to me

**Comment by Carpenteri1** [comment]
@rajgo1 atm I not sure I want to enable scrolling or have it. 
But you are always welcome to fork my project. :)
